services:
  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      spring.profiles.active: prod
      db.url: jdbc:mysql://somehost:3306/assignment_submission_db
      db.username: username
      db.password: password
    networks:
      - submission-app
    
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - 3000:3000
    depends_on:
      - back-end
    networks:
      - submission-app
  
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - front-end
    networks:
      - submission-app

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt
    command:
      - renew
        #      - certonly
        #      - --webroot
        #      - -w
        #      - /var/www/certbot/
        #      - --email=trevor@coderscampus.com
        #      - --agree-tos
        #      - --no-eff-email
        #      - -d
        #      - assignments.coderscampus.com

volumes:
  cert_home:

networks:
  submission-app: